#!/usr/bin/env python3
"""Deterministic generator for the packed Lean certificate modules.

Reads the canonical serialized streams (macro-scalar-tree/) and emits:
  data      -> MacroTreeWords.lean   (topology words, packed leaf blocks, counts)
  chunks    -> MacroTreeChunks/ChunkNNNN.lean  (one kernel-checked subtree replay each)
  assembly  -> MacroTreeAssembly.lean (internal node lemmas up to the root)
"""
from __future__ import annotations
import argparse, hashlib, json, struct, sys
from pathlib import Path
from fractions import Fraction as F
sys.setrecursionlimit(100000); sys.set_int_max_str_digits(0)
HERE=Path(__file__).resolve().parent
TREE=HERE.parent/'macro-scalar-tree'
LEAF_BITS=321; BLOCK=256
MOD='Zeta23.ThmD.Sextuple.Macro'

def load_streams():
    manifest=json.loads((TREE/'manifest.json').read_text())
    tc=manifest['token_count'];wc=(tc+19)//20
    top=(TREE/'topology-u64le.bin').read_bytes();assert len(top)==8*wc
    words=list(struct.unpack('<'+'Q'*wc,top))
    tokens=[(words[i//20]>>(3*(i%20)))&7 for i in range(tc)]
    kinds=(TREE/'terminal-kinds-u8.bin').read_bytes();assert len(kinds)==manifest['leaves']
    an=(TREE/'anchors-u16le.bin').read_bytes();tm=(TREE/'term-codes-u16le.bin').read_bytes()
    acodes=list(struct.unpack('<'+'H'*(len(an)//2),an));tcodes=list(struct.unpack('<'+'H'*(len(tm)//2),tm))
    assert len(acodes)==5*manifest['quadratic_leaves'] and len(tcodes)==15*manifest['quadratic_leaves']
    return manifest,words,tokens,kinds,acodes,tcodes

def leaf_words(manifest,kinds,acodes,tcodes):
    out=[];qc=0
    for k in kinds:
        if k==0: out.append(0);continue
        w=1
        for i in range(5): w|=acodes[5*qc+i]<<(1+16*i)
        for i in range(15): w|=tcodes[15*qc+i]<<(1+16*(5+i))
        assert w<(1<<LEAF_BITS); out.append(w);qc+=1
    assert qc==manifest['quadratic_leaves'];return out

def blocks_of(words):
    out=[]
    for s in range(0,len(words),BLOCK):
        b=0
        for j,w in enumerate(words[s:s+BLOCK]): b|=w<<(LEAF_BITS*j)
        out.append(b)
    return out

class Node:
    __slots__=('t0','p0','t1','p1','depth','axis','path','children','tokens')
def build_tree(tokens,kinds):
    """Build the explicit tree with cursors; path = list of (upper:bool, axis) root-first."""
    tc=0;pc=0
    def rec(depth,path):
        nonlocal tc,pc
        n=Node();n.t0=tc;n.p0=pc;n.depth=depth;n.path=path;n.children=[]
        tok=tokens[tc];tc+=1
        if tok:
            n.axis=tok-1
            n.children.append(rec(depth+1,path+[(False,n.axis)]))
            n.children.append(rec(depth+1,path+[(True,n.axis)]))
        else:
            n.axis=None;pc+=1
        n.t1=tc;n.p1=pc;n.tokens=n.t1-n.t0
        return n
    root=rec(0,[])
    assert tc==len(tokens) and pc==len(kinds)
    return root

def partition(root,max_tokens):
    """Greedy: a node becomes a chunk if its subtree has <= max_tokens tokens (or is a leaf)."""
    chunks=[];internal=[]
    def rec(n):
        if n.tokens<=max_tokens or not n.children:
            chunks.append(n);return
        internal.append(n)
        for c in n.children: rec(c)
    rec(root);return chunks,internal

def lean_path(path):
    # reversed: last step first, so pathBox root ((b,a)::rest) = (pathBox root rest).half a
    items=[f'({"true" if up else "false"}, {a})' for up,a in reversed(path)]
    return '['+', '.join(items)+']'

FUEL=61
HEADER_CHUNK='''import Zeta23.ThmD.Sextuple.Macro.TreeWords

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Zeta23.ThmD.Sextuple.MacroPrototype
open Zeta23.ThmD.Sextuple

'''
def replay_call(n,box_expr):
    return (f'replayAffineTree concreteLeafCheck topologyStream payloadStream {FUEL-n.depth} '
            f'{n.t0} {n.p0} ({box_expr})')

def emit_data(out,manifest,words,lwords):
    blocks=blocks_of(lwords)
    L=[f'import {MOD}.TreeReader','','/-! Generated by gen_packed.py from the canonical serialized streams. Do not edit. -/','','set_option maxRecDepth 100000','','noncomputable section','',
       'namespace Zeta23.ThmD.Sextuple.MacroPrototype','open Zeta23.ThmD.Sextuple','',
       f'def tokenCount : ℕ := {manifest["token_count"]}',f'def leafCount : ℕ := {manifest["leaves"]}','',
       'def topologyWords : Array ℕ := #['+', '.join(str(w) for w in words)+']','',
       'def leafBlocks : Array ℕ := #['+',\n  '.join(str(b) for b in blocks)+']','',
       'def topologyStream : CursorStream AffineTreeToken := packedTopologyStream tokenCount topologyWords','',
       'def payloadStream : CursorStream (AffineLeafPayload (MacroScalarLeaf 56 871)) := packedLeafStream leafCount leafBlocks','',
       'def rootBox : GapBox := initialGapBox 59','',
       'end Zeta23.ThmD.Sextuple.MacroPrototype','','end','']
    out.write_text('\n'.join(L))
    return blocks

def emit_chunk(path,idx,n):
    body=HEADER_CHUNK+f'/-- Subtree at topology cursor {n.t0}, payload cursor {n.p0}, depth {n.depth}, {n.tokens} tokens. -/\n'
    body+=f'theorem chunk{idx:04d} :\n    {replay_call(n, "pathBox rootBox "+lean_path(n.path))} =\n      some ({n.t1}, {n.p1}) := by\n  decide +kernel\n\n'
    body+='end Zeta23.ThmD.Sextuple.MacroPrototype\n'
    path.write_text(body)

def emit_assembly(out,root,chunks,internal,chunk_mod_prefix,group_size=None):
    """Emit internal-node lemmas in post-order. With group_size, split into chained part modules
    Macro/Assembly/PartNNN.lean (each importing the previous part and the chunks it references);
    TreeAssembly.lean then imports the last part and proves rootReplay."""
    names={}
    for i,c in enumerate(chunks): names[id(c)]=f'chunk{i:04d}'
    chunk_index={id(c):i for i,c in enumerate(chunks)}
    order=[]
    def rec(n):
        if id(n) in names: return
        for c in n.children: rec(c)
        order.append(n)
    rec(root)
    for i,n in enumerate(order): names[id(n)]=f'node{i:04d}'
    def node_lines(n):
        left,right=n.children;a=n.axis;pth=lean_path(n.path);L=[]
        L.append(f'theorem {names[id(n)]} :\n    {replay_call(n,"pathBox rootBox "+pth)} =\n      some ({n.t1}, {n.p1}) :=')
        L.append(f'  replayAffineTree_split_step (fuel := {FUEL-n.depth-1}) (t := {n.t0}) (p := {n.p0})')
        L.append(f'    (box := pathBox rootBox {pth}) (axis := {a})')
        L.append(f'    (tm := {left.t1}) (pm := {left.p1}) (t\' := {n.t1}) (p\' := {n.p1})')
        L.append(f'    (by decide +kernel) {names[id(left)]} {names[id(right)]}')
        L.append('')
        return L
    OPTS=[f'import {MOD}.AssemblyStep','','set_option maxHeartbeats 0','set_option maxRecDepth 100000','','namespace Zeta23.ThmD.Sextuple.MacroPrototype','open Zeta23.ThmD.Sextuple','']
    if group_size is None:
        L=[f'import {MOD}.TreeWords']+[f'import {MOD}.Chunks.Chunk{i:04d}' for i in range(len(chunks))]+OPTS
        for n in order: L+=node_lines(n)
        last_import=None
    else:
        d=out.parent/'Assembly';d.mkdir(exist_ok=True)
        groups=[order[i:i+group_size] for i in range(0,len(order),group_size)]
        for gi,g in enumerate(groups):
            imports=[f'import {MOD}.TreeWords']
            if gi>0: imports.append(f'import {MOD}.Assembly.Part{gi-1:03d}')
            needed=sorted({chunk_index[id(c)] for n in g for c in n.children if id(c) in chunk_index})
            imports+=[f'import {MOD}.Chunks.Chunk{i:04d}' for i in needed]
            G=imports+OPTS
            for n in g: G+=node_lines(n)
            G.append('end Zeta23.ThmD.Sextuple.MacroPrototype')
            (d/f'Part{gi:03d}.lean').write_text('\n'.join(G)+'\n')
        last_import=f'import {MOD}.Assembly.Part{len(groups)-1:03d}'
        L=[f'import {MOD}.TreeWords',last_import]+OPTS
    L.append(f'/-- The complete replay from the root consumes both streams exactly. -/')
    L.append(f'theorem rootReplay :\n    {replay_call(root,"rootBox")} =\n      some ({root.t1}, {root.p1}) := by')
    L.append(f'  have h := {names[id(root)]}')
    L.append(f'  simpa only [pathBox] using h')
    L.append('')
    L.append('end Zeta23.ThmD.Sextuple.MacroPrototype')
    out.write_text('\n'.join(L)+'\n')
    return order

def main():
    ap=argparse.ArgumentParser();ap.add_argument('cmd',choices=['data','chunks','assembly','stats'])
    ap.add_argument('--max-tokens',type=int,default=400);ap.add_argument('--out',type=Path,default=HERE)
    ap.add_argument('--chunk-prefix',default='Chunks');ap.add_argument('--only',type=int,default=None);ap.add_argument('--group-size',type=int,default=None)
    a=ap.parse_args();manifest,words,tokens,kinds,acodes,tcodes=load_streams();lwords=leaf_words(manifest,kinds,acodes,tcodes)
    root=build_tree(tokens,kinds);chunks,internal=partition(root,a.max_tokens)
    if a.cmd=='stats':
        sizes=[c.tokens for c in chunks];print('chunks',len(chunks),'internal',len(internal),'max',max(sizes),'min',min(sizes),'mean',sum(sizes)/len(sizes),'maxdepth',max(c.depth for c in chunks))
    elif a.cmd=='data':
        blocks=emit_data(a.out/'TreeWords.lean',manifest,words,lwords);print('blocks',len(blocks),'bytes',(a.out/'TreeWords.lean').stat().st_size)
    elif a.cmd=='chunks':
        d=a.out/a.chunk_prefix;d.mkdir(exist_ok=True)
        for i,c in enumerate(chunks):
            if a.only is not None and i!=a.only: continue
            emit_chunk(d/f'Chunk{i:04d}.lean',i,c)
        print('wrote',len(chunks) if a.only is None else 1,'chunks to',d)
    elif a.cmd=='assembly':
        order=emit_assembly(a.out/'TreeAssembly.lean',root,chunks,internal,a.chunk_prefix,a.group_size);print('internal nodes',len(order))
if __name__=='__main__':main()
